import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import path from 'path';
import { v4 as uuidv4 } from 'uuid';

const execAsync = promisify(exec);

/**
 * Converts a DOCX buffer to a PDF buffer using LibreOffice (via Command Line).
 * This is more reliable on Windows as it uses the absolute path to soffice.exe.
 */
export async function convertToPdf(docxBuffer: Buffer): Promise<Buffer> {
    const id = uuidv4();
    const tempDir = path.join(process.cwd(), 'public', 'templates', 'temp');
    
    // Ensure temp dir exists
    if (!fs.existsSync(tempDir)) {
        fs.mkdirSync(tempDir, { recursive: true });
    }

    const inputPath = path.join(tempDir, `${id}.docx`);
    const outputPath = path.join(tempDir, `${id}.pdf`);

    try {
        // 1. Write the buffer to a temporary docx file
        fs.writeFileSync(inputPath, docxBuffer);

        // 2. Get LibreOffice path from .env
        const sofficePath = process.env.LIBREOFFICE_PATH || 'soffice';
        
        // 3. Command: soffice --headless --convert-to pdf --outdir <tempDir> <inputPath>
        // Note: We use double quotes for paths to handle spaces in Windows
        const command = `"${sofficePath}" --headless --convert-to pdf --outdir "${tempDir}" "${inputPath}"`;
        
        console.log('Running conversion command:', command);
        await execAsync(command);

        // 4. Read the generated PDF
        if (!fs.existsSync(outputPath)) {
            throw new Error('PDF file was not generated by LibreOffice.');
        }
        
        const pdfBuffer = fs.readFileSync(outputPath);

        // 5. Cleanup
        fs.unlinkSync(inputPath);
        fs.unlinkSync(outputPath);

        return pdfBuffer;
    } catch (error: any) {
        console.error('Error converting DOCX to PDF:', error);
        
        // Cleanup on failure
        if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath);
        if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath);
        
        throw new Error(`Failed to convert document to PDF: ${error.message}. Ensure LibreOffice path in .env is correct.`);
    }
}
