import mammoth from 'mammoth';
import puppeteer from 'puppeteer';

/**
 * Converts a DOCX buffer to a PDF buffer using Mammoth (to HTML) and Puppeteer (to PDF).
 * This method does not require LibreOffice to be installed.
 */
export async function convertToPdf(docxBuffer: Buffer): Promise<Buffer> {
    try {
        // 1. Convert DOCX to HTML using Mammoth
        // We preserve as much styling as possible
        const { value: html } = await mammoth.convertToHtml({ buffer: docxBuffer });

        // 2. Wrap HTML in a professional document structure with CSS for better PDF output
        const styledHtml = `
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    @import url('https://fonts.googleapis.com/css2?family=Sarabun:wght@300;400;500;600;700&display=swap');
                    body {
                        font-family: 'Sarabun', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                        line-height: 1.6;
                        color: #333;
                        padding: 40px;
                        background: white;
                    }
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        margin-bottom: 20px;
                    }
                    table, th, td {
                        border: 1px solid #ddd;
                        padding: 8px;
                        text-align: left;
                    }
                    th {
                        background-color: #f2f2f2;
                    }
                    h1, h2, h3 {
                        color: #1a1a1a;
                    }
                    .footer {
                        margin-top: 50px;
                        font-size: 12px;
                        color: #777;
                        border-top: 1px solid #eee;
                        padding-top: 10px;
                    }
                </style>
            </head>
            <body>
                ${html}
                <div class="footer">
                    Generated by GenEDoc System - SSKRU
                </div>
            </body>
            </html>
        `;

        // 3. Launch Puppeteer and generate PDF
        const browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox'],
        });

        const page = await browser.newPage();
        await page.setContent(styledHtml, { waitUntil: 'networkidle0' });

        // Generate PDF buffer
        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: {
                top: '20mm',
                right: '20mm',
                bottom: '20mm',
                left: '20mm',
            },
        });

        await browser.close();
        
        // Return Uint8Array as Buffer
        return Buffer.from(pdfBuffer);
    } catch (error: unknown) {
        console.error('Error converting DOCX to PDF (Puppeteer):', error);
        const message = error instanceof Error ? error.message : 'Unknown error occurred';
        throw new Error(`Failed to convert document to PDF: ${message}`);
    }
}
